# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := core gfx

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

core: gfx
	@echo "==== Building core ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f core.make

gfx: 
	@echo "==== Building gfx ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f gfx.make

clean:
	@${MAKE} --no-print-directory -C . -f core.make clean
	@${MAKE} --no-print-directory -C . -f gfx.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   core"
	@echo "   gfx"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
