# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := core

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

core: 
	@echo "==== Building core ($(config)) ===="
	@${MAKE} --no-print-directory -C build/make -f Makefile

clean:
	@${MAKE} --no-print-directory -C build/make -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   core"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
