#ifndef GFX_DEFINES_HPP
#define GFX_DEFINES_HPP


#define GFX_SUCCESS 0
#define GFX_FAIL 1

#define GFX_INVALID_MATERIAL 2
#define GFX_INVALID_TEXTURE 3
#define GFX_INVALID_SHADER 4

#define GFX_INVALID_ANIMATION -1
#define GFX_INVALID_SKELETON -2


#endif